name: Update Schema

on: 
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        
      - name: Update Schema
        run: ./generate/create-pull-request.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
